###########################################################
# Input parameters required to drive RNA-Seq assembly suite
###########################################################

# provide path to genome file
genome: data/genome/genome.fa

# provide paired-end samples
# NOTE: only paired-end reads are supported currently. Please give path to R1 followed by R2 as below
# - if you have multiple reads of R1, R2, please combined them and provide as one R1 and one R2 file as shown below
# - if providing gzipped file, please use the extension '.gz'
# - you are free to provide a mix of uncompressed fastq files or gzipped files
# - the sample keys will be used for naming the output files [for e.g., Sample16, Sample17, Sample18]
samples:
    Sample16: [data/reads/Sample16.R1.fastq.gz,data/reads/Sample16.R2.fastq.gz]
    Sample17: [data/reads/Sample17.R1.fastq.gz,data/reads/Sample17.R2.fastq.gz]
    Sample18: [data/reads/Sample18.R1.fastq,data/reads/Sample18.R2.fastq]


# provide stranded option if the RNA-Seq samples are stranded
# User *MUST* include one of the below three options:
# - fr-firststrand, fr-secondstrand, unstranded
# Please refer below to select one:
# dUTP                  ==> fr-firststrand (Broad, BiooScientific, NEBNext)
# non-dUTP              ==> fr-secondstrand (NuGen, ScripSeq, directional TruSeq)
# unstranded            ==> unstranded
strandedness: fr-firststrand

# output folder name, NOT path
output: ./output
#####
# END of input parameters
#####

#######################
# source required tools and provide parameters
# NOTE: below tools are required for the RNA-Seq assembly pipeline
# ANext infers the folder name using second element (str.split(" ")),
# for e.g., from "source hisat-2.1.0", we use "hisat-2.1.0" as the folder name.
# So, please use the same format to source tools to the current $PATH
#######################
load:
  hisat2: "source hisat-2.1.0"
  samtools: "source samtools-1.7"
  stringtie: "source stringtie-1.3.3"
  scallop: "source scallop-0.10.2"
  portcullis: "source portcullis-1.1.2"
  # mikado: "source mikado-git_20190301"

# below you can modify or add parameters for the following tools that could be used when pipeline is executed
# NOTE: there are few options that we *CANNOT* provide as parameters (as described below).
# They are used internally within snakemake from options already given above.
load_parameters:
  # for hisat2 ignore option: --rna-strandness
  hisat2: "-q --phred33 --dta" # this is for hisat2 and not for hisat2_build
  # for stringtie ignore options: --rf, --fr
  stringtie: ""
  # for scallop ignore options: --library_type, -l
  scallop: "--verbose 0"
  # for portcullis ignore options: --output, --strandedness
  portcullis: "--orientation FR --canonical C,S --min_cov 2 --save_bad"

#####
# END of source tools and parameters
#####
